### ISSUE TITLE
Don't force-push tags!

### ISSUE THREAD

**Issue by wking** [SoftwareCarpentryLessonManager/lesson-manager#7]
Tags should be static, otherwise you should just be using branches.  I recommend we drop the [@@forceTag](https://github.com/SoftwareCarpentryLessonManager/lesson-manager/tree/eebdeb188da59e0486d437a3d3b57861294c1892#random-stuff) note added in eebdeb18 (shortcut to repush the tag, 2014-07-22).  If you do accidentally push the wrong v0.1.0 (for example), you should just tag v0.1.1 pointing at your original target.  In general, this is just thinking about what gets tagged (or pushed to master), because unwinding it after you've published it somewhere public is awkward.

**Comment by twitwi** [comment]
I totally agree with that. It was just to share with Raniere for the testing period (it was easier to force push the tags and clean the bower stuff when iterating quickly). I'll do that tomorrow (I'm on something completely unrelated at the time).
